name: everest_flutter_crypto_list
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable: ^6.3.2
  json_annotation: ^4.6.0
  dio: ^4.0.6
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  decimal: ^2.3.0
  fl_chart: ^0.55.1
  freezed: ^2.1.1
  brasil_fields: ^1.5.0
  currency_text_input_formatter: ^2.1.7
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/img/